// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox.sql

package db

import (
	"context"
	"database/sql"
)

const claimNewMentions = `-- name: ClaimNewMentions :many
UPDATE mentions SET notified_at = ?1
WHERE notified_at IS NULL AND handled = 0
RETURNING id, platform, kind, external_id, url, author, text, context, project_id, posted_at, seen_at, notified_at, handled
`

// Returns and marks in one statement, so two heartbeats never report the same item.
func (q *Queries) ClaimNewMentions(ctx context.Context, now sql.NullString) ([]Mention, error) {
	rows, err := q.db.QueryContext(ctx, claimNewMentions, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Kind,
			&i.ExternalID,
			&i.Url,
			&i.Author,
			&i.Text,
			&i.Context,
			&i.ProjectID,
			&i.PostedAt,
			&i.SeenAt,
			&i.NotifiedAt,
			&i.Handled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimNewReviews = `-- name: ClaimNewReviews :many
UPDATE reviews SET notified_at = ?1
WHERE notified_at IS NULL AND handled = 0
RETURNING id, store, app_id, project_id, external_id, rating, title, text, author, version, territory, posted_at, seen_at, notified_at, handled
`

func (q *Queries) ClaimNewReviews(ctx context.Context, now sql.NullString) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, claimNewReviews, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Store,
			&i.AppID,
			&i.ProjectID,
			&i.ExternalID,
			&i.Rating,
			&i.Title,
			&i.Text,
			&i.Author,
			&i.Version,
			&i.Territory,
			&i.PostedAt,
			&i.SeenAt,
			&i.NotifiedAt,
			&i.Handled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMention = `-- name: InsertMention :one

INSERT INTO mentions (
    platform, kind, external_id, url, author, text, context, project_id, posted_at, seen_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?10
)
ON CONFLICT (platform, external_id) DO NOTHING
RETURNING id
`

type InsertMentionParams struct {
	Platform   string
	Kind       string
	ExternalID string
	Url        string
	Author     string
	Text       string
	Context    string
	ProjectID  sql.NullInt64
	PostedAt   sql.NullString
	Now        string
}

// Mentions ------------------------------------------------------------------
// Conflict returns no row: the caller treats sql.ErrNoRows as "already known".
func (q *Queries) InsertMention(ctx context.Context, arg InsertMentionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertMention,
		arg.Platform,
		arg.Kind,
		arg.ExternalID,
		arg.Url,
		arg.Author,
		arg.Text,
		arg.Context,
		arg.ProjectID,
		arg.PostedAt,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertReview = `-- name: InsertReview :one

INSERT INTO reviews (
    store, app_id, project_id, external_id, rating, title, text, author, version,
    territory, posted_at, seen_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?10, ?11, ?12
)
ON CONFLICT (store, external_id) DO NOTHING
RETURNING id
`

type InsertReviewParams struct {
	Store      string
	AppID      string
	ProjectID  sql.NullInt64
	ExternalID string
	Rating     int64
	Title      string
	Text       string
	Author     string
	Version    string
	Territory  string
	PostedAt   sql.NullString
	Now        string
}

// Reviews -------------------------------------------------------------------
func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertReview,
		arg.Store,
		arg.AppID,
		arg.ProjectID,
		arg.ExternalID,
		arg.Rating,
		arg.Title,
		arg.Text,
		arg.Author,
		arg.Version,
		arg.Territory,
		arg.PostedAt,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listMentions = `-- name: ListMentions :many
SELECT id, platform, kind, external_id, url, author, text, context, project_id, posted_at, seen_at, notified_at, handled FROM mentions
WHERE (CAST(?1 AS BOOLEAN) IS NULL OR handled = CAST(?1 AS BOOLEAN))
  AND (CAST(?2 AS TEXT) IS NULL OR platform = CAST(?2 AS TEXT))
ORDER BY COALESCE(posted_at, seen_at) DESC
LIMIT ?3
`

type ListMentionsParams struct {
	Handled  sql.NullBool
	Platform sql.NullString
	Limit    int64
}

func (q *Queries) ListMentions(ctx context.Context, arg ListMentionsParams) ([]Mention, error) {
	rows, err := q.db.QueryContext(ctx, listMentions, arg.Handled, arg.Platform, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Kind,
			&i.ExternalID,
			&i.Url,
			&i.Author,
			&i.Text,
			&i.Context,
			&i.ProjectID,
			&i.PostedAt,
			&i.SeenAt,
			&i.NotifiedAt,
			&i.Handled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviews = `-- name: ListReviews :many
SELECT id, store, app_id, project_id, external_id, rating, title, text, author, version, territory, posted_at, seen_at, notified_at, handled FROM reviews
WHERE (CAST(?1 AS BOOLEAN) IS NULL OR handled = CAST(?1 AS BOOLEAN))
ORDER BY COALESCE(posted_at, seen_at) DESC
LIMIT ?2
`

type ListReviewsParams struct {
	Handled sql.NullBool
	Limit   int64
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listReviews, arg.Handled, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Store,
			&i.AppID,
			&i.ProjectID,
			&i.ExternalID,
			&i.Rating,
			&i.Title,
			&i.Text,
			&i.Author,
			&i.Version,
			&i.Territory,
			&i.PostedAt,
			&i.SeenAt,
			&i.NotifiedAt,
			&i.Handled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mentionsSeenSince = `-- name: MentionsSeenSince :many
SELECT id, platform, kind, external_id, url, author, text, context, project_id, posted_at, seen_at, notified_at, handled FROM mentions WHERE seen_at >= ?1 ORDER BY seen_at
`

func (q *Queries) MentionsSeenSince(ctx context.Context, since string) ([]Mention, error) {
	rows, err := q.db.QueryContext(ctx, mentionsSeenSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Kind,
			&i.ExternalID,
			&i.Url,
			&i.Author,
			&i.Text,
			&i.Context,
			&i.ProjectID,
			&i.PostedAt,
			&i.SeenAt,
			&i.NotifiedAt,
			&i.Handled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redactMentions = `-- name: RedactMentions :execrows
UPDATE mentions SET text = '', author = ''
WHERE platform = ?1 AND seen_at < ?2
  AND (text != '' OR author != '')
`

type RedactMentionsParams struct {
	Platform string
	Before   string
}

// Reddit's data policy asks for stored user content to be dropped within 48 h.
// The row stays (external_id keeps the import idempotent, url keeps the link).
func (q *Queries) RedactMentions(ctx context.Context, arg RedactMentionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, redactMentions, arg.Platform, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reviewsSeenSince = `-- name: ReviewsSeenSince :many
SELECT id, store, app_id, project_id, external_id, rating, title, text, author, version, territory, posted_at, seen_at, notified_at, handled FROM reviews WHERE seen_at >= ?1 ORDER BY seen_at
`

func (q *Queries) ReviewsSeenSince(ctx context.Context, since string) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, reviewsSeenSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Store,
			&i.AppID,
			&i.ProjectID,
			&i.ExternalID,
			&i.Rating,
			&i.Title,
			&i.Text,
			&i.Author,
			&i.Version,
			&i.Territory,
			&i.PostedAt,
			&i.SeenAt,
			&i.NotifiedAt,
			&i.Handled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMentionHandled = `-- name: SetMentionHandled :execrows
UPDATE mentions SET handled = 1, notified_at = COALESCE(notified_at, ?1)
WHERE id = ?2
`

type SetMentionHandledParams struct {
	Now sql.NullString
	ID  int64
}

func (q *Queries) SetMentionHandled(ctx context.Context, arg SetMentionHandledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setMentionHandled, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setReviewHandled = `-- name: SetReviewHandled :execrows
UPDATE reviews SET handled = 1, notified_at = COALESCE(notified_at, ?1)
WHERE id = ?2
`

type SetReviewHandledParams struct {
	Now sql.NullString
	ID  int64
}

func (q *Queries) SetReviewHandled(ctx context.Context, arg SetReviewHandledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setReviewHandled, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
