// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Mention struct {
	ID         int64
	Platform   string
	Kind       string
	ExternalID string
	Url        string
	Author     string
	Text       string
	Context    string
	ProjectID  sql.NullInt64
	PostedAt   sql.NullString
	SeenAt     string
	NotifiedAt sql.NullString
	Handled    bool
}

type Post struct {
	ID               int64
	ProjectID        int64
	Platform         string
	Kind             string
	Title            string
	Text             string
	MediaPath        string
	ReplyToUrl       string
	Warnings         string
	Status           string
	Revision         int64
	CreatedBy        string
	PostizPostID     string
	PostizGroup      string
	ReleaseUrl       string
	Error            string
	ScheduledAt      sql.NullString
	PublishedAt      sql.NullString
	ApprovedAt       sql.NullString
	ApprovedBy       string
	TelegramMsgID    sql.NullInt64
	NotifiedRevision int64
	CreatedAt        string
	UpdatedAt        string
}

type PostEvent struct {
	ID        int64
	PostID    int64
	Action    string
	Actor     string
	Detail    string
	Notified  bool
	CreatedAt string
}

type Project struct {
	ID              int64
	Slug            string
	Name            string
	Tagline         string
	Audience        string
	Tags            string
	Hooks           string
	ForbiddenClaims string
	WebsiteUrl      string
	StoreIosUrl     string
	StoreAndroidUrl string
	IosAppID        string
	AndroidPackage  string
	AssetsDir       string
	Status          string
	CreatedAt       string
	UpdatedAt       string
}

type Review struct {
	ID         int64
	Store      string
	AppID      string
	ProjectID  sql.NullInt64
	ExternalID string
	Rating     int64
	Title      string
	Text       string
	Author     string
	Version    string
	Territory  string
	PostedAt   sql.NullString
	SeenAt     string
	NotifiedAt sql.NullString
	Handled    bool
}
