// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"database/sql"
)

const addPostEvent = `-- name: AddPostEvent :exec
INSERT INTO post_events (post_id, action, actor, detail, notified, created_at)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6)
`

type AddPostEventParams struct {
	PostID   int64
	Action   string
	Actor    string
	Detail   string
	Notified bool
	Now      string
}

func (q *Queries) AddPostEvent(ctx context.Context, arg AddPostEventParams) error {
	_, err := q.db.ExecContext(ctx, addPostEvent,
		arg.PostID,
		arg.Action,
		arg.Actor,
		arg.Detail,
		arg.Notified,
		arg.Now,
	)
	return err
}

const approvePost = `-- name: ApprovePost :one
UPDATE posts
SET status = 'approved',
    approved_at = ?1,
    approved_by = ?2,
    scheduled_at = ?3,
    error = '',
    updated_at = ?1
WHERE id = ?4 AND status = 'draft' AND revision = ?5
RETURNING id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account
`

type ApprovePostParams struct {
	Now         sql.NullString
	Actor       string
	ScheduledAt sql.NullString
	ID          int64
	Revision    int64
}

func (q *Queries) ApprovePost(ctx context.Context, arg ApprovePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, approvePost,
		arg.Now,
		arg.Actor,
		arg.ScheduledAt,
		arg.ID,
		arg.Revision,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Kind,
		&i.Title,
		&i.Text,
		&i.MediaPaths,
		&i.ReplyToUrl,
		&i.Warnings,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.PostizPostID,
		&i.PostizGroup,
		&i.ReleaseUrl,
		&i.Error,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TelegramMsgID,
		&i.NotifiedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Account,
	)
	return i, err
}

const committedPostsBetween = `-- name: CommittedPostsBetween :many
SELECT id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account FROM posts
WHERE status IN ('approved', 'scheduled', 'published')
  AND platform = ?1
  AND account = ?2
  AND COALESCE(published_at, scheduled_at) >= ?3
  AND COALESCE(published_at, scheduled_at) < ?4
ORDER BY COALESCE(published_at, scheduled_at)
`

type CommittedPostsBetweenParams struct {
	Platform string
	Account  string
	From     sql.NullString
	To       sql.NullString
}

// Only the same account: two projects posting from two X accounts never
// compete for the same day.
func (q *Queries) CommittedPostsBetween(ctx context.Context, arg CommittedPostsBetweenParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, committedPostsBetween,
		arg.Platform,
		arg.Account,
		arg.From,
		arg.To,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.Kind,
			&i.Title,
			&i.Text,
			&i.MediaPaths,
			&i.ReplyToUrl,
			&i.Warnings,
			&i.Status,
			&i.Revision,
			&i.CreatedBy,
			&i.PostizPostID,
			&i.PostizGroup,
			&i.ReleaseUrl,
			&i.Error,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.TelegramMsgID,
			&i.NotifiedRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Account,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    project_id, platform, account, kind, title, text, media_paths, reply_to_url, warnings,
    created_by, status, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?10, 'draft', ?11, ?11
)
RETURNING id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account
`

type CreatePostParams struct {
	ProjectID  int64
	Platform   string
	Account    string
	Kind       string
	Title      string
	Text       string
	MediaPaths string
	ReplyToUrl string
	Warnings   string
	CreatedBy  string
	Now        string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ProjectID,
		arg.Platform,
		arg.Account,
		arg.Kind,
		arg.Title,
		arg.Text,
		arg.MediaPaths,
		arg.ReplyToUrl,
		arg.Warnings,
		arg.CreatedBy,
		arg.Now,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Kind,
		&i.Title,
		&i.Text,
		&i.MediaPaths,
		&i.ReplyToUrl,
		&i.Warnings,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.PostizPostID,
		&i.PostizGroup,
		&i.ReleaseUrl,
		&i.Error,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TelegramMsgID,
		&i.NotifiedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Account,
	)
	return i, err
}

const findPostByPostizRef = `-- name: FindPostByPostizRef :one
SELECT id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account FROM posts
WHERE (postiz_post_id != '' AND postiz_post_id = ?1)
   OR (postiz_group != '' AND postiz_group = ?1)
LIMIT 1
`

func (q *Queries) FindPostByPostizRef(ctx context.Context, ref string) (Post, error) {
	row := q.db.QueryRowContext(ctx, findPostByPostizRef, ref)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Kind,
		&i.Title,
		&i.Text,
		&i.MediaPaths,
		&i.ReplyToUrl,
		&i.Warnings,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.PostizPostID,
		&i.PostizGroup,
		&i.ReleaseUrl,
		&i.Error,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TelegramMsgID,
		&i.NotifiedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Account,
	)
	return i, err
}

const findPublishedByReleaseURL = `-- name: FindPublishedByReleaseURL :one
SELECT id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account FROM posts
WHERE platform = ?1 AND release_url != ''
  AND instr(release_url, ?2) > 0
ORDER BY id DESC
LIMIT 1
`

type FindPublishedByReleaseURLParams struct {
	Platform string
	Needle   string
}

func (q *Queries) FindPublishedByReleaseURL(ctx context.Context, arg FindPublishedByReleaseURLParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, findPublishedByReleaseURL, arg.Platform, arg.Needle)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Kind,
		&i.Title,
		&i.Text,
		&i.MediaPaths,
		&i.ReplyToUrl,
		&i.Warnings,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.PostizPostID,
		&i.PostizGroup,
		&i.ReleaseUrl,
		&i.Error,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TelegramMsgID,
		&i.NotifiedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Account,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account FROM posts WHERE id = ?
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Kind,
		&i.Title,
		&i.Text,
		&i.MediaPaths,
		&i.ReplyToUrl,
		&i.Warnings,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.PostizPostID,
		&i.PostizGroup,
		&i.ReleaseUrl,
		&i.Error,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TelegramMsgID,
		&i.NotifiedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Account,
	)
	return i, err
}

const listApprovedForPostiz = `-- name: ListApprovedForPostiz :many
SELECT id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account FROM posts
WHERE status = 'approved' AND platform != 'reddit'
ORDER BY scheduled_at, id
`

func (q *Queries) ListApprovedForPostiz(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listApprovedForPostiz)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.Kind,
			&i.Title,
			&i.Text,
			&i.MediaPaths,
			&i.ReplyToUrl,
			&i.Warnings,
			&i.Status,
			&i.Revision,
			&i.CreatedBy,
			&i.PostizPostID,
			&i.PostizGroup,
			&i.ReleaseUrl,
			&i.Error,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.TelegramMsgID,
			&i.NotifiedRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Account,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftsToNotify = `-- name: ListDraftsToNotify :many
SELECT id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account FROM posts
WHERE status = 'draft' AND notified_revision != revision
ORDER BY id
`

func (q *Queries) ListDraftsToNotify(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listDraftsToNotify)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.Kind,
			&i.Title,
			&i.Text,
			&i.MediaPaths,
			&i.ReplyToUrl,
			&i.Warnings,
			&i.Status,
			&i.Revision,
			&i.CreatedBy,
			&i.PostizPostID,
			&i.PostizGroup,
			&i.ReleaseUrl,
			&i.Error,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.TelegramMsgID,
			&i.NotifiedRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Account,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostEvents = `-- name: ListPostEvents :many
SELECT id, post_id, "action", actor, detail, notified, created_at FROM post_events WHERE post_id = ? ORDER BY id
`

func (q *Queries) ListPostEvents(ctx context.Context, postID int64) ([]PostEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPostEvents, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostEvent{}
	for rows.Next() {
		var i PostEvent
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Action,
			&i.Actor,
			&i.Detail,
			&i.Notified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account FROM posts
WHERE (CAST(?1 AS TEXT) IS NULL OR status = CAST(?1 AS TEXT))
  AND (CAST(?2 AS INTEGER) IS NULL OR project_id = CAST(?2 AS INTEGER))
  AND (CAST(?3 AS TEXT) IS NULL OR platform = CAST(?3 AS TEXT))
ORDER BY id DESC
LIMIT ?4
`

type ListPostsParams struct {
	Status    sql.NullString
	ProjectID sql.NullInt64
	Platform  sql.NullString
	Limit     int64
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts,
		arg.Status,
		arg.ProjectID,
		arg.Platform,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.Kind,
			&i.Title,
			&i.Text,
			&i.MediaPaths,
			&i.ReplyToUrl,
			&i.Warnings,
			&i.Status,
			&i.Revision,
			&i.CreatedBy,
			&i.PostizPostID,
			&i.PostizGroup,
			&i.ReleaseUrl,
			&i.Error,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.TelegramMsgID,
			&i.NotifiedRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Account,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduled = `-- name: ListScheduled :many
SELECT id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account FROM posts WHERE status = 'scheduled' ORDER BY scheduled_at, id
`

func (q *Queries) ListScheduled(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listScheduled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.Kind,
			&i.Title,
			&i.Text,
			&i.MediaPaths,
			&i.ReplyToUrl,
			&i.Warnings,
			&i.Status,
			&i.Revision,
			&i.CreatedBy,
			&i.PostizPostID,
			&i.PostizGroup,
			&i.ReleaseUrl,
			&i.Error,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.TelegramMsgID,
			&i.NotifiedRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Account,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnnotifiedEvents = `-- name: ListUnnotifiedEvents :many
SELECT id, post_id, "action", actor, detail, notified, created_at FROM post_events WHERE notified = 0 ORDER BY id LIMIT 50
`

func (q *Queries) ListUnnotifiedEvents(ctx context.Context) ([]PostEvent, error) {
	rows, err := q.db.QueryContext(ctx, listUnnotifiedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostEvent{}
	for rows.Next() {
		var i PostEvent
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Action,
			&i.Actor,
			&i.Detail,
			&i.Notified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventNotified = `-- name: MarkEventNotified :exec
UPDATE post_events SET notified = 1 WHERE id = ?
`

func (q *Queries) MarkEventNotified(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEventNotified, id)
	return err
}

const markFailed = `-- name: MarkFailed :one
UPDATE posts
SET status = 'failed',
    error = ?1,
    updated_at = ?2
WHERE id = ?3 AND status IN ('approved', 'scheduled')
RETURNING id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account
`

type MarkFailedParams struct {
	Error string
	Now   string
	ID    int64
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, markFailed, arg.Error, arg.Now, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Kind,
		&i.Title,
		&i.Text,
		&i.MediaPaths,
		&i.ReplyToUrl,
		&i.Warnings,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.PostizPostID,
		&i.PostizGroup,
		&i.ReleaseUrl,
		&i.Error,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TelegramMsgID,
		&i.NotifiedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Account,
	)
	return i, err
}

const markPublished = `-- name: MarkPublished :one
UPDATE posts
SET status = 'published',
    published_at = ?1,
    release_url = ?2,
    error = '',
    updated_at = ?3
WHERE id = ?4 AND status IN ('approved', 'scheduled')
RETURNING id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account
`

type MarkPublishedParams struct {
	PublishedAt sql.NullString
	ReleaseUrl  string
	Now         string
	ID          int64
}

func (q *Queries) MarkPublished(ctx context.Context, arg MarkPublishedParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, markPublished,
		arg.PublishedAt,
		arg.ReleaseUrl,
		arg.Now,
		arg.ID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Kind,
		&i.Title,
		&i.Text,
		&i.MediaPaths,
		&i.ReplyToUrl,
		&i.Warnings,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.PostizPostID,
		&i.PostizGroup,
		&i.ReleaseUrl,
		&i.Error,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TelegramMsgID,
		&i.NotifiedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Account,
	)
	return i, err
}

const markScheduled = `-- name: MarkScheduled :one
UPDATE posts
SET status = 'scheduled',
    postiz_post_id = ?1,
    postiz_group = ?2,
    scheduled_at = ?3,
    error = '',
    updated_at = ?4
WHERE id = ?5 AND status = 'approved'
RETURNING id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account
`

type MarkScheduledParams struct {
	PostizPostID string
	PostizGroup  string
	ScheduledAt  sql.NullString
	Now          string
	ID           int64
}

func (q *Queries) MarkScheduled(ctx context.Context, arg MarkScheduledParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, markScheduled,
		arg.PostizPostID,
		arg.PostizGroup,
		arg.ScheduledAt,
		arg.Now,
		arg.ID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Kind,
		&i.Title,
		&i.Text,
		&i.MediaPaths,
		&i.ReplyToUrl,
		&i.Warnings,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.PostizPostID,
		&i.PostizGroup,
		&i.ReleaseUrl,
		&i.Error,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TelegramMsgID,
		&i.NotifiedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Account,
	)
	return i, err
}

const postLog = `-- name: PostLog :many
SELECT id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account FROM posts
WHERE status IN ('approved', 'scheduled', 'published')
  AND COALESCE(published_at, scheduled_at, approved_at) >= ?1
ORDER BY COALESCE(published_at, scheduled_at, approved_at) DESC
`

// What went out (or is committed to go out) and when. The agent reads this
// before every proposal.
func (q *Queries) PostLog(ctx context.Context, since sql.NullString) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, postLog, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.Kind,
			&i.Title,
			&i.Text,
			&i.MediaPaths,
			&i.ReplyToUrl,
			&i.Warnings,
			&i.Status,
			&i.Revision,
			&i.CreatedBy,
			&i.PostizPostID,
			&i.PostizGroup,
			&i.ReleaseUrl,
			&i.Error,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.TelegramMsgID,
			&i.NotifiedRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Account,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postsCreatedSince = `-- name: PostsCreatedSince :many
SELECT id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account FROM posts
WHERE created_at >= ?1
ORDER BY id
`

// Every post created in the window, whatever its fate: re-proposing a text
// that was rejected is as pointless as repeating a published one.
func (q *Queries) PostsCreatedSince(ctx context.Context, since string) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, postsCreatedSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.Kind,
			&i.Title,
			&i.Text,
			&i.MediaPaths,
			&i.ReplyToUrl,
			&i.Warnings,
			&i.Status,
			&i.Revision,
			&i.CreatedBy,
			&i.PostizPostID,
			&i.PostizGroup,
			&i.ReleaseUrl,
			&i.Error,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.TelegramMsgID,
			&i.NotifiedRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Account,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectPost = `-- name: RejectPost :one
UPDATE posts
SET status = 'rejected',
    error = ?1,
    updated_at = ?2
WHERE id = ?3 AND status IN ('draft', 'approved', 'failed')
RETURNING id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account
`

type RejectPostParams struct {
	Reason string
	Now    string
	ID     int64
}

func (q *Queries) RejectPost(ctx context.Context, arg RejectPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, rejectPost, arg.Reason, arg.Now, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Kind,
		&i.Title,
		&i.Text,
		&i.MediaPaths,
		&i.ReplyToUrl,
		&i.Warnings,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.PostizPostID,
		&i.PostizGroup,
		&i.ReleaseUrl,
		&i.Error,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TelegramMsgID,
		&i.NotifiedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Account,
	)
	return i, err
}

const retryPost = `-- name: RetryPost :one
UPDATE posts
SET status = 'approved',
    error = '',
    scheduled_at = ?1,
    updated_at = ?2
WHERE id = ?3 AND status = 'failed'
RETURNING id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account
`

type RetryPostParams struct {
	ScheduledAt sql.NullString
	Now         string
	ID          int64
}

// A failed post goes back to approved so the publisher picks it up again.
func (q *Queries) RetryPost(ctx context.Context, arg RetryPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, retryPost, arg.ScheduledAt, arg.Now, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Kind,
		&i.Title,
		&i.Text,
		&i.MediaPaths,
		&i.ReplyToUrl,
		&i.Warnings,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.PostizPostID,
		&i.PostizGroup,
		&i.ReleaseUrl,
		&i.Error,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TelegramMsgID,
		&i.NotifiedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Account,
	)
	return i, err
}

const setPostError = `-- name: SetPostError :exec
UPDATE posts SET error = ?1, updated_at = ?2 WHERE id = ?3
`

type SetPostErrorParams struct {
	Error string
	Now   string
	ID    int64
}

// Transient publisher error: keep the state, remember why it did not move.
func (q *Queries) SetPostError(ctx context.Context, arg SetPostErrorParams) error {
	_, err := q.db.ExecContext(ctx, setPostError, arg.Error, arg.Now, arg.ID)
	return err
}

const setPostNotified = `-- name: SetPostNotified :exec
UPDATE posts
SET telegram_msg_id = ?1,
    notified_revision = ?2
WHERE id = ?3
`

type SetPostNotifiedParams struct {
	TelegramMsgID sql.NullInt64
	Revision      int64
	ID            int64
}

func (q *Queries) SetPostNotified(ctx context.Context, arg SetPostNotifiedParams) error {
	_, err := q.db.ExecContext(ctx, setPostNotified, arg.TelegramMsgID, arg.Revision, arg.ID)
	return err
}

const updateDraftContent = `-- name: UpdateDraftContent :one
UPDATE posts
SET text = ?1,
    title = ?2,
    media_paths = ?3,
    warnings = ?4,
    revision = revision + 1,
    updated_at = ?5
WHERE id = ?6 AND status = 'draft'
RETURNING id, project_id, platform, kind, title, text, media_paths, reply_to_url, warnings, status, revision, created_by, postiz_post_id, postiz_group, release_url, error, scheduled_at, published_at, approved_at, approved_by, telegram_msg_id, notified_revision, created_at, updated_at, account
`

type UpdateDraftContentParams struct {
	Text       string
	Title      string
	MediaPaths string
	Warnings   string
	Now        string
	ID         int64
}

func (q *Queries) UpdateDraftContent(ctx context.Context, arg UpdateDraftContentParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updateDraftContent,
		arg.Text,
		arg.Title,
		arg.MediaPaths,
		arg.Warnings,
		arg.Now,
		arg.ID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Kind,
		&i.Title,
		&i.Text,
		&i.MediaPaths,
		&i.ReplyToUrl,
		&i.Warnings,
		&i.Status,
		&i.Revision,
		&i.CreatedBy,
		&i.PostizPostID,
		&i.PostizGroup,
		&i.ReleaseUrl,
		&i.Error,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TelegramMsgID,
		&i.NotifiedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Account,
	)
	return i, err
}
