// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const findProjectByAppID = `-- name: FindProjectByAppID :one
SELECT id, slug, name, tagline, audience, tags, hooks, forbidden_claims, website_url, store_ios_url, store_android_url, ios_app_id, android_package, assets_dir, status, created_at, updated_at FROM projects
WHERE (ios_app_id != '' AND ios_app_id = ?1)
   OR (android_package != '' AND android_package = ?1)
LIMIT 1
`

func (q *Queries) FindProjectByAppID(ctx context.Context, appID string) (Project, error) {
	row := q.db.QueryRowContext(ctx, findProjectByAppID, appID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.Audience,
		&i.Tags,
		&i.Hooks,
		&i.ForbiddenClaims,
		&i.WebsiteUrl,
		&i.StoreIosUrl,
		&i.StoreAndroidUrl,
		&i.IosAppID,
		&i.AndroidPackage,
		&i.AssetsDir,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, slug, name, tagline, audience, tags, hooks, forbidden_claims, website_url, store_ios_url, store_android_url, ios_app_id, android_package, assets_dir, status, created_at, updated_at FROM projects WHERE id = ?
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.Audience,
		&i.Tags,
		&i.Hooks,
		&i.ForbiddenClaims,
		&i.WebsiteUrl,
		&i.StoreIosUrl,
		&i.StoreAndroidUrl,
		&i.IosAppID,
		&i.AndroidPackage,
		&i.AssetsDir,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, name, tagline, audience, tags, hooks, forbidden_claims, website_url, store_ios_url, store_android_url, ios_app_id, android_package, assets_dir, status, created_at, updated_at FROM projects WHERE slug = ?
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.Audience,
		&i.Tags,
		&i.Hooks,
		&i.ForbiddenClaims,
		&i.WebsiteUrl,
		&i.StoreIosUrl,
		&i.StoreAndroidUrl,
		&i.IosAppID,
		&i.AndroidPackage,
		&i.AssetsDir,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, name, tagline, audience, tags, hooks, forbidden_claims, website_url, store_ios_url, store_android_url, ios_app_id, android_package, assets_dir, status, created_at, updated_at FROM projects
WHERE CAST(?1 AS TEXT) IS NULL OR status = CAST(?1 AS TEXT)
ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context, status sql.NullString) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tagline,
			&i.Audience,
			&i.Tags,
			&i.Hooks,
			&i.ForbiddenClaims,
			&i.WebsiteUrl,
			&i.StoreIosUrl,
			&i.StoreAndroidUrl,
			&i.IosAppID,
			&i.AndroidPackage,
			&i.AssetsDir,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (
    slug, name, tagline, audience, tags, hooks, forbidden_claims, website_url,
    store_ios_url, store_android_url, ios_app_id, android_package, assets_dir,
    status, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?10, ?11,
    ?12, ?13, ?14,
    ?15, ?15
)
ON CONFLICT (slug) DO UPDATE SET
    name              = excluded.name,
    tagline           = excluded.tagline,
    audience          = excluded.audience,
    tags              = excluded.tags,
    hooks             = excluded.hooks,
    forbidden_claims  = excluded.forbidden_claims,
    website_url       = excluded.website_url,
    store_ios_url     = excluded.store_ios_url,
    store_android_url = excluded.store_android_url,
    ios_app_id        = excluded.ios_app_id,
    android_package   = excluded.android_package,
    assets_dir        = excluded.assets_dir,
    status            = excluded.status,
    updated_at        = excluded.updated_at
RETURNING id, slug, name, tagline, audience, tags, hooks, forbidden_claims, website_url, store_ios_url, store_android_url, ios_app_id, android_package, assets_dir, status, created_at, updated_at
`

type UpsertProjectParams struct {
	Slug            string
	Name            string
	Tagline         string
	Audience        string
	Tags            string
	Hooks           string
	ForbiddenClaims string
	WebsiteUrl      string
	StoreIosUrl     string
	StoreAndroidUrl string
	IosAppID        string
	AndroidPackage  string
	AssetsDir       string
	Status          string
	Now             string
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, upsertProject,
		arg.Slug,
		arg.Name,
		arg.Tagline,
		arg.Audience,
		arg.Tags,
		arg.Hooks,
		arg.ForbiddenClaims,
		arg.WebsiteUrl,
		arg.StoreIosUrl,
		arg.StoreAndroidUrl,
		arg.IosAppID,
		arg.AndroidPackage,
		arg.AssetsDir,
		arg.Status,
		arg.Now,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.Audience,
		&i.Tags,
		&i.Hooks,
		&i.ForbiddenClaims,
		&i.WebsiteUrl,
		&i.StoreIosUrl,
		&i.StoreAndroidUrl,
		&i.IosAppID,
		&i.AndroidPackage,
		&i.AssetsDir,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
