// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tributes.sql

package db

import (
	"context"
	"database/sql"
)

const cancelTribute = `-- name: CancelTribute :one
UPDATE tributes
SET status = 'cancelled', updated_at = ?1
WHERE id = ?2 AND status IN ('queued', 'failed')
RETURNING id, project_id, credit, source_path, note, status, post_id, styles, error, submitted_by, created_at, updated_at
`

type CancelTributeParams struct {
	Now string
	ID  int64
}

func (q *Queries) CancelTribute(ctx context.Context, arg CancelTributeParams) (Tribute, error) {
	row := q.db.QueryRowContext(ctx, cancelTribute, arg.Now, arg.ID)
	var i Tribute
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Credit,
		&i.SourcePath,
		&i.Note,
		&i.Status,
		&i.PostID,
		&i.Styles,
		&i.Error,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimTribute = `-- name: ClaimTribute :one
UPDATE tributes
SET status = 'running', updated_at = ?1
WHERE id = (SELECT id FROM tributes WHERE status = 'queued' ORDER BY id LIMIT 1)
RETURNING id, project_id, credit, source_path, note, status, post_id, styles, error, submitted_by, created_at, updated_at
`

// Claim the oldest queued tribute for this run. The status change is the lock:
// a second worker started by accident finds nothing left to take.
func (q *Queries) ClaimTribute(ctx context.Context, now string) (Tribute, error) {
	row := q.db.QueryRowContext(ctx, claimTribute, now)
	var i Tribute
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Credit,
		&i.SourcePath,
		&i.Note,
		&i.Status,
		&i.PostID,
		&i.Styles,
		&i.Error,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countQueuedTributes = `-- name: CountQueuedTributes :one
SELECT COUNT(*) FROM tributes WHERE status = 'queued'
`

func (q *Queries) CountQueuedTributes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueuedTributes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueTribute = `-- name: EnqueueTribute :one
INSERT INTO tributes (project_id, credit, source_path, note, submitted_by, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?6)
RETURNING id, project_id, credit, source_path, note, status, post_id, styles, error, submitted_by, created_at, updated_at
`

type EnqueueTributeParams struct {
	ProjectID   int64
	Credit      string
	SourcePath  string
	Note        string
	SubmittedBy string
	Now         string
}

func (q *Queries) EnqueueTribute(ctx context.Context, arg EnqueueTributeParams) (Tribute, error) {
	row := q.db.QueryRowContext(ctx, enqueueTribute,
		arg.ProjectID,
		arg.Credit,
		arg.SourcePath,
		arg.Note,
		arg.SubmittedBy,
		arg.Now,
	)
	var i Tribute
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Credit,
		&i.SourcePath,
		&i.Note,
		&i.Status,
		&i.PostID,
		&i.Styles,
		&i.Error,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTribute = `-- name: GetTribute :one
SELECT id, project_id, credit, source_path, note, status, post_id, styles, error, submitted_by, created_at, updated_at FROM tributes WHERE id = ?
`

func (q *Queries) GetTribute(ctx context.Context, id int64) (Tribute, error) {
	row := q.db.QueryRowContext(ctx, getTribute, id)
	var i Tribute
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Credit,
		&i.SourcePath,
		&i.Note,
		&i.Status,
		&i.PostID,
		&i.Styles,
		&i.Error,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTributes = `-- name: ListTributes :many
SELECT id, project_id, credit, source_path, note, status, post_id, styles, error, submitted_by, created_at, updated_at FROM tributes
WHERE CAST(?1 AS TEXT) IS NULL OR status = CAST(?1 AS TEXT)
ORDER BY id DESC
LIMIT ?2
`

type ListTributesParams struct {
	Status sql.NullString
	Limit  int64
}

func (q *Queries) ListTributes(ctx context.Context, arg ListTributesParams) ([]Tribute, error) {
	rows, err := q.db.QueryContext(ctx, listTributes, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tribute{}
	for rows.Next() {
		var i Tribute
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Credit,
			&i.SourcePath,
			&i.Note,
			&i.Status,
			&i.PostID,
			&i.Styles,
			&i.Error,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueTribute = `-- name: RequeueTribute :one
UPDATE tributes
SET status = 'queued', error = '', updated_at = ?1
WHERE id = ?2 AND status IN ('failed', 'cancelled')
RETURNING id, project_id, credit, source_path, note, status, post_id, styles, error, submitted_by, created_at, updated_at
`

type RequeueTributeParams struct {
	Now string
	ID  int64
}

// A failed tribute goes back in the queue; cancelling drops it for good.
func (q *Queries) RequeueTribute(ctx context.Context, arg RequeueTributeParams) (Tribute, error) {
	row := q.db.QueryRowContext(ctx, requeueTribute, arg.Now, arg.ID)
	var i Tribute
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Credit,
		&i.SourcePath,
		&i.Note,
		&i.Status,
		&i.PostID,
		&i.Styles,
		&i.Error,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tributeDrafted = `-- name: TributeDrafted :one
UPDATE tributes
SET status = 'drafted',
    post_id = ?1,
    styles = ?2,
    error = '',
    updated_at = ?3
WHERE id = ?4 AND status = 'running'
RETURNING id, project_id, credit, source_path, note, status, post_id, styles, error, submitted_by, created_at, updated_at
`

type TributeDraftedParams struct {
	PostID sql.NullInt64
	Styles string
	Now    string
	ID     int64
}

func (q *Queries) TributeDrafted(ctx context.Context, arg TributeDraftedParams) (Tribute, error) {
	row := q.db.QueryRowContext(ctx, tributeDrafted,
		arg.PostID,
		arg.Styles,
		arg.Now,
		arg.ID,
	)
	var i Tribute
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Credit,
		&i.SourcePath,
		&i.Note,
		&i.Status,
		&i.PostID,
		&i.Styles,
		&i.Error,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tributeFailed = `-- name: TributeFailed :one
UPDATE tributes
SET status = 'failed', error = ?1, updated_at = ?2
WHERE id = ?3 AND status IN ('queued', 'running')
RETURNING id, project_id, credit, source_path, note, status, post_id, styles, error, submitted_by, created_at, updated_at
`

type TributeFailedParams struct {
	Error string
	Now   string
	ID    int64
}

func (q *Queries) TributeFailed(ctx context.Context, arg TributeFailedParams) (Tribute, error) {
	row := q.db.QueryRowContext(ctx, tributeFailed, arg.Error, arg.Now, arg.ID)
	var i Tribute
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Credit,
		&i.SourcePath,
		&i.Note,
		&i.Status,
		&i.PostID,
		&i.Styles,
		&i.Error,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
